version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/be/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
  frontend:
    build:
      context: ./
      dockerfile: ./docker/fe/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env
